# Generated by Django 5.0.7 on 2024-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='کاربر ناشناس', max_length=20)),
                ('age', models.IntegerField()),
                ('gen', models.CharField(choices=[('f', 'famel'), ('m', 'mel')], max_length=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
